src/components/Text/Text.tsx
도현 회원님의 요청에 따라서 Text 공용 컴포넌트에 className 프롭을 옵셔널로 추가해뒀습니다.
=> Text 공용 컴포넌트에 className 프롭 추가했습니다

src/App.tsx, src/components/Text/Text.tsx, src/pages/Case/Case.module.css, src/pages/Case/Case.tsx, src/pages/index.ts, src/root.css
- Text.tsx 공용 컴포넌트의 props 타입을 "string"에서 string으로 수정했습니다.
- root.css에 margin 옵션 중에 --margin-250을 --margin-300으로 수정했습니다.
- App.tsx의 값을 초기화시켜뒀습니다.
=> Text.tsx 공용 컴포넌트 props 수정, root.css 값 수정, App.tsx 수정

src/containers/Layers/Layers.module.css, src/pages/Case/Case.module.css, src/root.css
- Case 페이지 컴포넌트의 Layers UI 크기를 수정해 스타일을 완성했습니다.
=> Case 컴포넌트 UI 완성

src/assets/arrow-up.svg, src/components/DropdownMenu/DropdownMenu.tsx
- DropdownMenu 컴포넌트는 toggle 상태변수의 값에 따라 렌더링되는 결과값이 달라집니다.
- toggle 상태변수는 기본값을 false를 가지지만 true가 된다면 메뉴 목록을 리스트 렌더링해서 보여줍니다.
- 리스트 렌더링되는 값은 현재 임의로 넣어뒀습니다.
=> DropdownMenu 공용 컴포넌트 UI 완성했습니다

src/components/Badge/Badge.module.css, src/components/Badge/Badge.tsx
=> Badge 컴포넌트 수정

src/components/Text/Text.module.css, src/components/Text/Text.tsx, src/root.css
기존의 variant prop을 제거하고, 스타일이 구분되던 것을 없엤습니다. className과 children prop만 남겨뒀으며 className은
옵셔널로 사용이 가능합니다.
새로운 디자인에 따라 기존 값을 수정했으며, 새로운 값들을 추가해뒀습니다.
=> Text 공용 컴포넌트 수정 및 root.css 값 추가/수정

src/components/Carousel/Carousel.module.css, src/components/Carousel/Carousel.tsx, src/components/Title/Title.module.css, src/introSwiper.css
- 피그마 시안과 동일하게 텍스트 container 마진을 top, left 100px씩 적용하여 수정하였습니다.
- 피그마 시안과 동일하게 font-size와 위 아래 margin값을 줄였습니다.
- 바로가기 버튼을 왼쪽으로 배치하고 top 마진을 100px 적용하여 수정하였습니다.
=> 디자인 시안 변경으로 인한 Intro 페이지, Title 컴포넌트 스타일 일부 수정했습니다.

src/components/Carousel/Carousel.tsx, src/containers/IntroInfo/IntroInfo.module.css, src/detailSwiper.css
- useNavigate()를 이용하여 button의 onclick에 각 페이지로 가는 함수를 넣어서 구현하였습니다.
- 스와이퍼에 스타일이 겹쳐서 Intro 페이지에서 오류가 나는 부분들을 확인하고 수정하였습니다.
=> Intro 페이지에 페이지 바로가기 기능을 연결했습니다.

src/containers/DetailCarousel/DetailCarousel.tsx
- detailCarousel container에 불필요한 주석을 제거하였습니다.
- swiper의 slideto 기능을 이용하여 index에 해당하는 슬라이드로 이동하는 기능을 구현하였습니다.
=> detall Carousel의 slideto로 원하는 슬라이드로 이동할 수 있는 기능 추가

src/components/DropdownMenu/DropdownMenu.tsx
=> [🔧수정] DropdownMenu 컴포넌트 토클 방향 수정

src/utils/checkUserCookie.ts, src/utils/deleteUserCookie.ts, src/utils/index.ts
- user_auth 쿠키를 확인해주는 함수와 삭제하는 함수입니다.
=> [✨기능] user_auth 쿠키 확인 및 삭제 함수

src/utils/createUserCookie.ts, src/utils/deleteUserCookie.ts, src/utils/index.ts
- 편안한 개발을 위해 가짜 쿠키를 만들어주는 함수를 만들었습니다
=> 가짜 쿠키를 만드는 함수를 추가했습니다

src/App.tsx, src/containers/DetailCarousel/DetailCarousel.tsx, src/containers/DetailForm/DetailForm.tsx, src/pages/Detail/Detail.tsx
- home 페이지에서 전달된 id를 detail에서 받았습니다.
- 받은 id와 각 json에 있는 id의 일치여부를 확인하여 데이터를 가져옵니다.
- id는 undefined로 전달되어 불가피하게 string | undefined의 타입을 지정하였습니다.
- number 타입으로 받을 수 있는 해결방법을 아시는 분은 코멘트 부탁드립니다.
=> useParams를 사용하여 Detail <-> home 페이지 연결하였습니다.

src/containers/Card/Card.module.css, src/containers/Card/Card.tsx, src/pages/School/School.tsx
- 경북대학교와 고려대학교 클릭시 카드 컴포넌트 색상 변경했습니다.
=> School 페이지 학교 렌더링 시 카드컴포넌트 색상변경 

src/components/Navigation/Navigation.module.css, src/containers/DetailCarousel/DetailCarousel.module.css, src/containers/Header/Header.module.css, src/containers/Header/Header.tsx, src/pages/School/School.module.css
- 서당페이지 이동하기 Link 추가
- Header 고정
- 서당, T3Q.ai 체험하기 hover 색 추가
- 홈 화면 이동 추가
=> 서당페이지 이동하기 추가, Header 고정했습니다.

package-lock.json, package.json, src/atoms/index.ts, src/atoms/resultAtom.ts, src/components/Spinner/Spinner.module.css, src/components/Spinner/Spinner.tsx
Spinner 공통 컴포넌트의 디자인은 위와 같습니다.
- 비동기 통신 중 로딩 처리를 위해 Spinner 공통 컴포넌트를 개발하였습니다.
- Spinner 공통 컴포넌트는 react-spinners 라이브러리를 사용하여 개발되었습니다. (npm i)
- resultAtom 파일을 만들어 결과 컴포넌트 출력을 고려하였습니다.
=> 비동기 통신 중 로딩 처리를 위해 Spinner 컴포넌트 제작하였습니다.

src/axios/case28/audio/audio_anomaly.tsx, src/axios/case28/audio/audio_classification.tsx, src/axios/case28/audio/audio_clustering.tsx, src/axios/case28/audio/audio_regression.tsx, src/axios/case28/binary/binary_anomaly.tsx, src/axios/case28/binary/binary_classification.tsx, src/axios/case28/binary/binary_clustering.tsx, src/axios/case28/binary/binary_regression.tsx, src/axios/case28/image/image_anomaly.tsx, src/axios/case28/image/image_classification.tsx, src/axios/case28/image/image_clustering.tsx, src/axios/case28/image/image_regression.tsx, src/axios/case28/log/log_anomaly.tsx, src/axios/case28/log/log_classification.tsx, src/axios/case28/log/log_clustering.tsx, src/axios/case28/log/log_regression.tsx, src/axios/case28/satellite/satellite_anomaly.tsx, src/axios/case28/satellite/satellite_classification.tsx, src/axios/case28/satellite/satellite_clustering.tsx, src/axios/case28/satellite/satellite_regression.tsx, src/axios/case28/text/text_anomaly.ts, src/axios/case28/text/text_classification.ts, src/axios/case28/text/text_clustering.ts, src/axios/case28/text/text_regression.ts, src/axios/case28/video/video_anomaly.tsx, src/axios/case28/video/video_classification.tsx, src/axios/case28/video/video_regression.tsx
=> axios 함수에 결과값 추가했습니다.

src/axios/case28/image/image_anomaly.tsx, src/axios/combinedAxios.ts, src/containers/DetailForm/DetailForm.tsx
- axios 함수들을 id 값과 일치하도록 순차적으로 배열에 담았습니다.
- 각 함수들은 detailForm에서 넘어온 pageId 값을 이용하여 배열의 index로 호출하였습니다.
- detailForm에서 71번 라인에 타입 관련 오류가 있어 수정하였습니다.
- 서버와 통신되면 정상결과가 받아지는지 테스트가 필요합니다.
- 함수 중 오타가 있는 부분을 수정하였습니다.
=> ID 값을 활용하여 각 예제에 맞는 axios 함수를 호출할 수 있도록 변경하였습니다.

src/containers/Header/Header.module.css
=> Header 반응형 수정했습니다.

index.html, src/components/Book/Book.module.css, src/components/Book/Book.tsx, src/components/Canvas/Canvas.tsx, src/components/DropdownMenu/DropdownMenu.module.css, src/components/DropdownMenu/DropdownMenu.tsx, src/containers/DetailCarousel/DetailCarousel.module.css, src/containers/DetailCarousel/DetailCarousel.tsx, src/containers/DetailForm/DetailForm.tsx, src/containers/Header/Header.tsx, src/pages/Detail/Detail.module.css, src/pages/Detail/Detail.tsx
- index 언어 부분 ko로 변경했습니다.
```tsx
return (
<button
type="button"
className={`${className} ${styles.Book}`}
onClick={handleBook}
aria-label="북마크하기"
>
{book === false ? <BookmarkEmpty /> : <BookmarkFill />}
</button>
)
}
```
- 찜 기능 태그를 `button`으로 바꾸고 `aria-label` 속성으로 기능에 대한 설명 추가했습니다.
```tsx
<div className={`${styles.dropDown} ${className}`} onClick={handleToggle}> 
```
- `onClick` 위치를 메뉴 전체를 감싸고 있는 div로 옮겨 화살표 외 다른 범위를 클릭하여도 드롭다운메뉴가 펼쳐지도록 바꾸었습니다.
```tsx
return (
<section className={styles.container}>
```
- 감싸고 있는 컨테이너 태그를 section으로 변경했습니다.
- Book 컴포넌트를 논리적 구조를 위해 위치를 캐러셀 컴포넌트 안이 아닌 `Detail.tsx` 컴포넌트로 옮겼습니다.
```tsx
return (
<section className={styles.container}>
<Title
```
- 감싸고 있는 컨테이너를 section 태그로 수정했습니다.
```tsx
return (
<header className={styles.header}>
<div …
```
=> 접근성 부분 마크업, 스타일링 몇 가지 수정했습니다.

vite.config.ts
vite.config.ts에서 server:true로 변경
=> host 속성 true로 변경

package-lock.json, package.json, src/main.tsx, src/pages/Detail/Detail.tsx, src/pages/Home/Home.tsx, src/pages/School/School.tsx
- main.tsx 에서 ```<HelmetProvider>```를 추가해 react-helmet-async에서 제공하는 ```<Helmet>``` 컴포넌트를 사용하여 각각의 컴포넌트에서 동적으로 문서의 head 부분(페이지 제목, 메타 태그 등)을 관리할 수 있음
- 페이지별로 ```<Helmet>``` 컴포넌트 안에 ```<title>```, ```<meta>``` 태그 추가
=> react-helmet-async 패키지 설치 후 SEO 최적화

src/App.tsx, src/components/CartLayer/CartLayer.module.css, src/components/CartLayer/CartLayer.tsx, src/components/CartTable/CartTable.tsx, src/components/PrivateRoute/PrivateRoute.tsx, src/components/Spinner/Spinner.module.css, src/components/Table/Table.tsx, src/containers/Header/Header.tsx, src/containers/HomeCase/HomeCase.module.css, src/containers/HomeCase/HomeCase.tsx, src/hooks/useBook.ts, src/keycloak.ts, src/pages/Detail/Detail.tsx
=> Spinner 컴포넌트 스타일 작업

src/components/Table/Table.tsx
접근제한기능을 주석처리하여 상세페이지에 접근할 수 있도록 해뒀습니다
=> 상세페이지 접근제한기능 임시차단

src/axios/case28/text/text_classification.ts, src/components/Table/Table.tsx, src/containers/HomeCase/HomeCase.tsx, src/containers/VisionModal/VisionModal.module.css, src/pages/Detail/Detail.tsx
- 추론하기 버튼을 누르면 결과를 받아오는 동안 로딩 스피너가 동작합니다.
- 스피너는 Detail Page 에서 렌더링 됩니다.
- Recoil을 이용하여 로딩 스피너가 상태관리됩니다.
=> 추론하기 버튼에 Spinner 로딩 컴포넌트를 적용하였습니다.

src/axios/vision/classification/mobilenet_classification.ts, src/axios/vision/classification/vit_classification.ts, src/axios/vision/classification/yolov5_classification.ts, src/axios/vision/classification/yolov8_classification.ts, src/axios/vision/detection/yolor_detection.ts, src/axios/vision/detection/yolos_detection.ts, src/axios/vision/detection/yolov3_keras_detection.ts, src/axios/vision/detection/yolov3_torch_detection.ts, src/axios/vision/detection/yolov5_detection.ts, src/axios/vision/detection/yolov6_detection.ts, src/axios/vision/detection/yolov7_detection.ts, src/axios/vision/detection/yolov8_detection.ts, src/axios/vision/detection/yolox_detection.ts, src/axios/vision/division/maskrcnn_segmentation.ts, src/axios/vision/division/segformer_segmentation.ts, src/axios/vision/division/yolov5_segmentation.ts, src/axios/vision/division/yolov7_segmentation.ts, src/axios/vision/division/yolov8_segmentation.ts, src/axios/vision/etc/detectron_detection.ts, src/axios/vision/etc/scaled_yolov4_detection.ts, src/axios/vision/etc/yolov4_tiny_detection.ts, src/axios/vision/etc/yolov4_torch_detection.ts
=> vision 예제 비동기 axios 함수 생성했습니다.

src/axios/case28/video/video_classification.tsx, src/axios/convertVideo.ts, src/axios/getSubPageData.ts, src/containers/DetailForm/DetailForm.tsx, src/utils/addMimeType.ts
- 비디오 행동 분류 예제에서 파일을 선택할시 데이터 통신 요청이 들어가고, 받아온 변환 데이터를 화면에 렌더링하는 기능 구현
- 추론 결과 값이 제대로 안 들어오는 현상이 있어 값을 제대로 바꿔주는 로직 추가
=> 비디오 변환 기능 추가

src/App.tsx, src/atoms/index.ts, src/atoms/userIdAtom.ts, src/components/CartLayer/CartLayer.tsx, src/components/CartTable/CartTable.tsx, src/containers/Header/Header.tsx, src/hooks/useBook.ts
- 사용자가 로그인을 할 경우, 고유 ID값을 확인해 장바구니에 데이터를 추가 혹은 제거할 수 있는 기능을 완성했습니다.
- 사용자가 로그인이 될 경우, 쿠키에 담겨온 ID값이 state에 담겨 API 통신이 가능해집니다. 사용자가 로그아웃을 할 경우
쿠키가 제거되면서  ID값도 자동으로 공백이 됩니다.
- 사용자가 로그인이 되지 않았을 경우, 장바구니 레이어는 비어있게 됩니다.
=> 사용자 정보에 따른 장바구니 기능

src/axios/case28/video/video_clustering.tsx, src/axios/combinedAxios.ts, src/axios/school/korea/ku_1202.tsx, src/axios/school/korea/ku_1204.tsx, src/axios/vision/classification/vit_classification.ts, src/axios/vision/classification/yolov8_classification.ts
- video_clustering에 해당하는 비동기 통신함수를 작성하였습니다.
- 해당 예제는 다른 예제와 다르게 이미지와 값 둘다 반환하여 보여주고 있습니다.
- 따라서 resultData에 이미지, extraData에 결과값을 넣어서 배열형식으로 return 하도록 구현하였습니다.
=> video_clustering 예제에 맞는 비동기 통신함수 작성하였습니다.

src/axios/case28/video/video_clustering.tsx
resultData에 extraData를 문자열로 합해서 반환하도록 수정하였습니다.
=> video_clustering 비동기 통신 코드 return 수정하였습니다.

src/axios/case28/video/video_clustering.tsx, src/components/Result/Result.tsx
=> [✨기능] 얼굴 키포인트가 있는 데이터 군집화 결과 렌더링 기능

src/axios/getSubPageData.ts, src/components/index.ts, src/containers/index.ts, src/pages/Detail/Detail.tsx
로딩 기능을 추가하여 데이터를 다 받아올 때까지 로딩 스피너가 보이도록 바꾸었습니다.
=> detail 페이지 통신 함수 로딩 추가

src/axios/school/korea/ku_1200.ts, src/axios/school/korea/ku_1201.ts, src/axios/school/korea/ku_1202.ts, src/axios/school/korea/ku_1203.ts, src/axios/school/korea/ku_1204.ts, src/axios/school/korea/ku_1205.ts, src/axios/school/kyungpook/knu_1100.ts, src/axios/school/kyungpook/knu_1101.ts, src/axios/school/kyungpook/knu_1102.ts
=> 서당 페이지 axiosInstance 적용

src/axios/convertVideo.ts, src/axios/vision/classification/mobilenet_classification.ts, src/axios/vision/classification/vit_classification.ts, src/axios/vision/classification/yolov5_classification.ts, src/axios/vision/classification/yolov8_classification.ts, src/axios/vision/detection/yolor_detection.ts, src/axios/vision/detection/yolos_detection.ts, src/axios/vision/detection/yolov3_keras_detection.ts, src/axios/vision/detection/yolov3_torch_detection.ts, src/axios/vision/detection/yolov5_detection.ts, src/axios/vision/detection/yolov6_detection.ts, src/axios/vision/detection/yolov7_detection.ts, src/axios/vision/detection/yolov8_detection.ts, src/axios/vision/detection/yolox_detection.ts, src/axios/vision/division/maskrcnn_segmentation.ts, src/axios/vision/division/segformer_segmentation.ts, src/axios/vision/division/yolov5_segmentation.ts, src/axios/vision/division/yolov7_segmentation.ts, src/axios/vision/division/yolov8_segmentation.ts, src/axios/vision/etc/detectron_detection.ts, src/axios/vision/etc/sample_code.ts, src/axios/vision/etc/scaled_yolov4_detection.ts, src/axios/vision/etc/yolov4_tiny_detection.ts, src/axios/vision/etc/yolov4_torch_detection.ts, src/components/Result/Result.tsx, src/containers/DetailForm/DetailForm.tsx, src/utils/handleNavigate.ts
axiosInstance를 사용해 url을 호출 할 수 있도록 코드 수정
=> 비전 예제 axiosInstance 적용

src/hooks/useBook.ts
- 장바구니가 28개에 도달했을 경우 최대 갯수에 도달했다는 경고를 띄우도록 해뒀습니다!
=> 장바구니 초과 경고 알림 기능

src/atoms/detailDataAtom.ts, src/axios/base64DataToFile.ts, src/axios/convertVideo.ts, src/axios/getSubPageData.ts, src/containers/DetailForm/DetailForm.tsx, src/pages/Detail/Detail.tsx
any 타입 수정, 맡은 코드에서 eslint 경고 뜨는 부분 수정했습니다.
=> DetailForm, getSubPageData any 타입 수정

src/App.tsx, src/atoms/cartAtom.ts, src/atoms/isLoggedInAtom.ts, src/atoms/userIdAtom.ts, src/axios/case28/video/video_regression.ts, src/components/CartTable/CartTable.tsx, src/components/Table/Table.tsx, src/containers/AI28Modal/AI28Modal.tsx, src/containers/VisionModal/VisionModal.tsx, src/utils/handleNavigate.ts, src/utils/preventBubbling.ts
- cartTable.tsx, getSubPageData.ts, video_regression.ts에서 host와 port를 제거했습니다
=> Port, Host 제거

src/components/Input/Input.module.css, src/components/Result/Result.module.css, src/components/Result/Result.tsx
base64 문자열 내에 'and' 가 포함 되어있을 가능성을 간과해서 생긴 버그였습니다. 조금 더 상세한 조건 처리를 통해 해결했습니다.
또한 이미지가 잘려보이지 않게 하기 위해 css를 수정했습니다.
=> [🐞버그] base64 이미지 처리 버그 수정

src/components/DropdownMenu/DropdownMenu.module.css, src/containers/Header/Header.module.css, src/data/layers/VISION_LAYER.json
회의에서 언급되었던 수정사항 작업 마무리했습니다. 
- 비전 레이어 아코디언 오타 수정
- DropdownMenu 컴포넌트 클릭 범위 확장
- Header 색상 변경
=> JSON 값 수정, 드롭박스 클릭 범위 확장, 네비게이션 색상 변경

src/axios/getSubPageData.ts, src/components/ApiURL/ApiURL.tsx, src/components/Log/Log.module.css, src/components/Log/Log.tsx, src/containers/DetailForm/DetailForm.tsx, src/pages/Detail/Detail.tsx, src/utils/addMimeType.ts
-로그 입력예제 사용자 접근제한/스크롤 스타일 변경
- 추론하기 안되는 예제도 접근해서 화면은 보이게끔
- 추가된 서당 예제 데이터 화면 렌더링 확인
금일 회의에서 나온 프론트엔드 피드백 맡은 사항 작업 완료 했습니다.
=> 금일 회의 피드백 반영

src/components/Canvas/Canvas.module.css, src/components/Canvas/Canvas.tsx, src/components/Keyword/Keyword.tsx
- 이미지 분류 예제 모바일 대응 기능 추가
- 키워드 추론 결과 값이 undefined인 경우, 빈 키워드 컴포넌트가 나오는 것을 확인했습니다. 추론 실패의 경우 '추론 결과 없음' 이라는 텍스트가 들어간 키워드 컴포넌트가 출력 되도록 수정했습니다.
=> 이미지 분류 예제 모바일 대응 기능 추가

src/App.tsx, src/atoms/index.ts, src/atoms/isModalOpenAtom.ts, src/components/CartLayer/CartLayer.module.css, src/components/CartTable/CartTable.tsx, src/components/Layers/Layers.tsx, src/components/LayersView/LayersView.tsx, src/components/Table/Table.tsx, src/components/VisionAccordion/VisionAccordion.tsx, src/containers/AI28Modal/AI28Modal.tsx, src/containers/CartModal/CartModal.tsx, src/containers/VisionModal/VisionModal.tsx, src/global.css
- CartLayer에 Item의 문장이 길면 여백을 다 차지하는 걸 방지하기 위해 스타일값을 조정했습니다.
- 레이어와 관련된 모달창이 화면에 보이는 상황에도 body의 스크롤에 접근이 가능한 걸 제거했습니다
=> 장바구니 폰트 크기 조정, 스크롤바 제거

src/components/AlertModal/AlertModal.tsx, src/hooks/useBook.ts
- alert()를 사용하지 않고, 경고창 컴포넌트를 활용해 장바구니 기능을 수정했습니다.
=> 장바구니 기능을 수행할 때 컴포넌트를 적용했습니다

src/components/AlertModal/AlertModal.tsx, src/components/RecordButton/RecordButton.tsx
- 음성녹음이 실패했을 때에도 음성녹음 관련 Atom값이 바뀌어 정상 동작하는 것처럼 보이던 문제를 해결하였습니다.
- 음성 녹음과 관련한 에러 메세지를 알림 컴포넌트에 추가하였습니다.
=> 음성 녹음 관련한 알림창과 버그 수정하였습니다.

src/atoms/index.ts, src/atoms/tableAtom.ts, src/pages/Home/Home.tsx
=> 불필요한 파일 및 코드 제거

src/components/DropdownMenu/DropdownMenu.tsx, src/containers/DetailCarousel/DetailCarousel.tsx, src/containers/DetailForm/DetailForm.tsx, src/pages/Detail/Detail.tsx
=> [🔧수정] 레이어 이동 시 state 유지되는 버그 수정

src/axios/convertVideo.ts, src/axios/getSubPageData.ts, src/components/Input/Input.tsx, src/containers/DetailForm/DetailForm.tsx
이전처럼 변환된 데이터를 추론 요청하는 것이 아닌 서버에서 받아온 원본 데이터로 추론 요청하게 수정했습니다.
=> [🔧수정] 비디오 변환 전 데이터로 추론 요청 기능 추가

src/axios/vision/visionProcessor.ts
=> vision 함수 수정했습니다.

src/App.tsx, src/containers/Header/Header.tsx
```
useEffect(() => {
if(keycloak.authenticated || userAuth) {
setIsLoggedIn(true)
} else {
setIsLoggedIn(false)
}
}, [keycloak.authenticated, userAuth])
```
Header.tsx 안에서 useEffect를 추가하여 Header의 UI가 즉시 변경될 수 있도록 해뒀습니다.
=> 헤더 느린 업데이트 버그 해결

src/containers/DetailCarousel/DetailCarousel.tsx, src/data/PPT_DATA.json
- 확장성과 수정작업을 편하게 하기 위해 배열안에 객체로 들어가있던 데이터를 객체를 제거하고 배열형식으로 만들었습니다.
- 그에 따라 DetailCarousel.tsx에서 목차를 가져오는 코드가 형식에 맞게 수정되었습니다.
=> PPT 데이터 중 목차를 배열[객체, 객체...] 형식에서 배열 형식으로 변경

src/App.tsx, src/hooks/_index.ts, src/hooks/useUserCookie.ts
- 사용자가 로그인을 했을 경우 생겨난 쿠키가 남아있을 경우 사용자가 로그인을 하지 않았더라도 개인AI로 데이터가 불려오는 버그를 수정했습니다
=> 남아있는 쿠키로 인한 개인 AI 데이터 패칭 버그 수정

src/axios/case28/audioProcessor.ts, src/axios/case28/binaryProcessor.ts, src/axios/case28/imageProcessor.ts, src/axios/case28/logProcessor.ts, src/axios/case28/satelliteProcessor.ts, src/axios/case28/textProcessor.ts, src/axios/case28/videoProcessor.ts, src/axios/combinedProcessor.ts, src/axios/school/schoolProcessor.ts
- 기존 targetId가 any로 지정하여 사용하였지만 string으로 지정하여주었습니다.
- 문서화 작업 관련하여 주석 및 라인 정리하였습니다.
=> 추론하기 함수에서 targetId의 타입을 지정해주었습니다. 
